name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Cloud Run
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: capstone-ro1
          service_account_key: ${{ secrets.GCP_SERVICE_KEY }}

      - name: Export Service Account Key
        run: echo "${{ secrets.GCP_SERVICE_KEY }}" > key.json

      - name: Authenticate with Service Account
        run: gcloud auth activate-service-account --key-file=key.json

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy deploy-model \
            --source=. \
            --platform=managed \
            --region=asia-southeast2 \
            --allow-unauthenticated
