name: 'Build and Deploy to Cloud Run'

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: 'capstone-ro1'
  REGION: 'asia-southeast2' 
  SERVICE: 'deploy-model'
  WORKLOAD_IDENTITY_PROVIDER: 'projects/1044914573456/locations/global/workloadIdentityPools/github-pool/providers/github-actions'

jobs:
  deploy:
    runs-on: 'ubuntu-latest'

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      # Step 1: Checkout source code dari repository
      - name: 'Checkout'
        uses: 'actions/checkout@v4'

      # Step 2: Debugging Context untuk memastikan struktur token
      - name: Debug GitHub Context
        run: |
          echo "Repository: ${{ github.repository }}"
          echo "Actor: ${{ github.actor }}"
          echo "Workflow: ${{ github.workflow }}"

      # Step 3: Autentikasi ke Google Cloud menggunakan Workload Identity Federation
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: '${{ env.WORKLOAD_IDENTITY_PROVIDER }}'
          service_account: 'ro-cc-api@capstone-ro1.iam.gserviceaccount.com' 

      # Step 4: Autentikasi Docker untuk Artifact Registry
      - name: 'Docker Auth'
        uses: 'docker/login-action@v3'
        with:
          username: 'oauth2accesstoken'
          password: '${{ steps.auth.outputs.token }}'
          registry: '${{ env.REGION }}-docker.pkg.dev'

      # Step 5: Build dan Push Docker Image ke Artifact Registry
      - name: 'Build and Push Container'
        run: |-
          DOCKER_TAG="${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.SERVICE }}:${{ github.sha }}"
          docker build --tag "${DOCKER_TAG}" .
          docker push "${DOCKER_TAG}"

      # Step 6: Deploy ke Cloud Run menggunakan Docker Image terbaru
      - name: 'Deploy to Cloud Run'
        uses: 'google-github-actions/deploy-cloudrun@v2'
        with:
          service: '${{ env.SERVICE }}'
          region: '${{ env.REGION }}'
          image: '${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.SERVICE }}:${{ github.sha }}'

      # Step 7: Tampilkan URL Cloud Run untuk verifikasi
      - name: 'Show output'
        run: echo ${{ steps.deploy.outputs.url }}
